// front/src/pages/users/Users.tsx
import { useEffect, useState } from "react";
import GenericTable, { type Column } from "../../components/GenericTable";
import Modal from "../../components/Modal";
import IconPencil from "../../icons/IconPencil";
import IconTrash from "../../icons/IconTrash";
import { useSearchParams } from "react-router-dom";
import { IPaginationResult } from "@/shared/interfaces/pagination.interface";
import { GetUser } from "@/modules/users/interfaces/get-user";
import { UserService } from "../../modules/users/services/user.service";
import { Formik } from "formik";
import { CreateOrUpdateUser } from "@/modules/users/interfaces/create-or-update-user";
import { validationSchema } from "./utils";
import { BaseResponse } from "@/shared/services/base.service";
import { toast } from "react-toastify";

const userService = new UserService();
const formEmpty: CreateOrUpdateUser = {
  name: "",
  gender: "hombre",
  age: 0,
  identification: "",
  phone: "",
  address: "",
  clientId: "",
  password: "",
};

function Users() {
  const [showForm, setShowModal] = useState(false);
  const [searchParams, setSearchParams] = useSearchParams();
  const [data, setData] = useState<IPaginationResult<GetUser> | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [editId, setEditId] = useState<string | null>(null);
  const [initialValues, setInitialValues] =
    useState<CreateOrUpdateUser>(formEmpty);

  const columns: Column<GetUser>[] = [
    { key: "name", label: "Nombre" },
    { key: "identification", label: "identification" },

    { key: "gender", label: "Genero" },
    { key: "age", label: "Edad" },
    { key: "phone", label: "Telefono" },
    { key: "address", label: "Dirrecion" },
    { key: "clientId", label: "ID Cliente" },

    {
      key: "actions",
      label: "Acciones",
      render: (_, row) => (
        <div className="table-actions">
          <button onClick={() => handleActionEdit(row)} className="btn-edit">
            <IconPencil />
          </button>
          <button
            onClick={() => {
              handleClickDelete(row.id);
            }}
            className="btn-delete"
          >
            <IconTrash />
          </button>
        </div>
      ),
    },
  ];

  useEffect(() => {
    (async () => {
      await initialize();
    })();
  }, []);

  const initialize = async () => {
    await getAll();
  };

  const getAll = async (q = "") => {
    const page = searchParams.get("page") ?? 1;
    const query = q ?? searchParams.get("query") ?? "";

    try {
      setIsLoading(true);
      const result = await userService.getAllPaginated<GetUser>({
        page: Number(page),
        query,
      });

      setData(result.data.data);
    } catch (error) {
      console.log("Error:" + error);
    } finally {
      setIsLoading(false);
    }
  };

  const onSubmit = async (values: CreateOrUpdateUser) => {
    try {
      let msg = "Creando con éxito";
      if (editId) {
        await userService.edit(editId, values);
        msg = "Actualizado con éxito";
      } else {
        await userService.post<CreateOrUpdateUser, BaseResponse<string>>(
          values
        );
      }

      toast(msg, { type: "success" });

      await getAll();
      setEditId(null);
      setInitialValues(formEmpty);
      setShowModal(false);
    } catch (error) {
      console.log(error);
    }
  };

  const handleChangeSearch = async (e: React.ChangeEvent<HTMLInputElement>) => {
    setSearchParams({ query: e.target.value });

    await getAll(e.target.value);
  };

  const handleActionEdit = (data: GetUser) => {
    setEditId(data.id);

    setInitialValues({
      ...data,
    });

    setShowModal(true);
  };

  const handleClickDelete = async (id: string) => {
    if (!id) return;

    const result = confirm("¿Está seguro de que desea eliminar este cliente?");
    if (!result) return;

    try {
      const { data, status } = await userService.remove(id);

      if (status != 204 && !data.success) {
        toast(data.message, { type: "error" });
        return;
      }

      toast("Cliente eliminado con éxito", { type: "success" });
      await getAll();
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <section>
      <h2>Clientes</h2>
      <div className="section-header">
        <input type="text" onChange={handleChangeSearch} placeholder="Buscar" />
        <button onClick={() => setShowModal(true)} className="btn">
          Nuevo
        </button>
      </div>
      <div className="client-list">
        {isLoading ? (
          <div className="loading">Cargando...</div>
        ) : (
          data && (
            <GenericTable
              columns={columns}
              data={data}
              currentPage={Number(searchParams.get("page")) || 1}
              onChangePage={(page) => {
                setSearchParams({ page: String(page) });
                getAll();
              }}
            />
          )
        )}
      </div>
      <Modal
        open={showForm}
        onClose={() => setShowModal(false)}
        title="Nuevo cliente"
        description="Ingrese los datos del nuevo cliente"
      >
        <Formik
          onSubmit={onSubmit}
          initialValues={initialValues}
          validationSchema={validationSchema}
          enableReinitialize
        >
          {({ values, errors, handleChange, handleSubmit }) => (
            <form className="form" onSubmit={handleSubmit}>
              <label>Nombre:</label>
              <input
                name="name"
                value={values.name}
                onChange={handleChange}
                placeholder="Nombre cliente"
              />
              <span className="text-danger">{errors.name}</span>
              <label>Genero:</label>
              <select
                name="gender"
                value={values.gender}
                onChange={handleChange}
              >
                <option value="hombre">Hombre</option>
                <option value="mujer">Mujer</option>
              </select>

              <label>Edad:</label>
              <input
                name="age"
                value={values.age}
                onChange={handleChange}
                type="number"
                placeholder="Edad del cliente"
                required
              />
              <span className="text-danger">{errors.age}</span>

              <label>Identificación:</label>
              <input
                name="identification"
                value={values.identification}
                onChange={handleChange}
                type="text"
                placeholder="Identificación del cliente"
              />
              <span className="text-danger">{errors.identification}</span>

              <label>Teléfono:</label>
              <input
                name="phone"
                value={values.phone}
                onChange={handleChange}
                type="text"
                placeholder="Teléfono del cliente"
              />
              <span className="text-danger">{errors.phone}</span>

              <label>Dirección:</label>
              <input
                name="address"
                value={values.address}
                onChange={handleChange}
                type="text"
                placeholder="Dirección del cliente"
              />
              <span className="text-danger">{errors.address}</span>

              <label>ID Cliente:</label>
              <input
                name="clientId"
                value={values.clientId}
                onChange={handleChange}
                type="text"
                placeholder="ID del cliente"
              />
              <span className="text-danger">{errors.clientId}</span>

              <label>Contraseña:</label>
              <input
                name="password"
                value={values.password}
                onChange={handleChange}
                type="password"
                placeholder="Contraseña del cliente"
              />
              <span className="text-danger">{errors.password}</span>

              <button type="submit" className="btn form-btn">
                Guardar
              </button>
            </form>
          )}
        </Formik>
      </Modal>
    </section>
  );
}

export default Users;

// front-angular/src/app/users/users.ts
import { Component, OnInit } from '@angular/core';
import { IPaginationResult } from '../../shared/interfaces/pagination.interface';
import { GetUser } from './interfaces/get-user';
import { CreateOrUpdateUser } from './interfaces/create-or-update-user';
import { UserService } from './services/user.service';
import { Column, TableComponent } from '../shared/table/table';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule, FormGroup, FormBuilder, Validators } from '@angular/forms';
 

const formEmpty: CreateOrUpdateUser = {
  name: "",
  gender: "hombre",
  age: 0,
  identification: "",
  phone: "",
  address: "",
  clientId: "",
  password: "",
};

@Component({
  selector: 'app-users',
  standalone: false,
  templateUrl: './users.html',
  styleUrl: './users.css',
})
export class Users implements OnInit {
  showForm: boolean = false;
  data: IPaginationResult<GetUser> | null = null;
  isLoading: boolean = false;
  editId: string | null = null;
  initialValues: CreateOrUpdateUser = formEmpty;
  searchQuery: string = '';
  userForm: FormGroup;

  columns: Column<GetUser>[] = [
    { key: 'name', label: 'Nombre' },
    { key: 'identification', label: 'Identificación' },
    { key: 'gender', label: 'Genero' },
    { key: 'age', label: 'Edad' },
    { key: 'phone', label: 'Teléfono' },
    { key: 'address', label: 'Dirección' },
    { key: 'clientId', label: 'ID Cliente' },
    {
      key: 'actions',
      label: 'Acciones',
      render: (value: unknown, row: GetUser) => `
       <div>
        <button class="btn-edit" data-action="edit" data-id="${row.id}">Editar</button>
        <button class="btn-delete" data-action="delete" data-id="${row.id}">Eliminar</button>
       </div>
      `,
    },
  ];

  constructor(private userService: UserService, private fb: FormBuilder) {
    this.userForm = this.fb.group({
      name: ['', Validators.required],
      gender: ['hombre', Validators.required],
      age: ['', [Validators.required, Validators.min(18), Validators.pattern(/^[0-9]*$/)]],
      identification: ['', [Validators.required, Validators.pattern(/^[0-9]*$/)]],
      phone: ['', [Validators.required, Validators.pattern(/^[0-9]*$/)]],
      address: ['', Validators.required],
      clientId: ['', Validators.required],
      password: ['', [Validators.required, Validators.minLength(6)]]
    });
  }

  ngOnInit(): void {
    this.initialize();
  }

  initialize(): void {
    this.getAll();
  }

  getAll(q: string = this.searchQuery, page: number = 1): void {
    this.isLoading = true;
    try {
      this.userService
        .getAllPaginated<GetUser>({
          page: page,
          query: q
        })
        .subscribe({
          next: (result) => {
            this.data = result.data;
          },
          error: (error) => {
            console.error('Error:' + error);
          },
        });
    } catch (error) {
      console.error('Error:' + error);
    } finally {
      this.isLoading = false;
    }
  }

  onSubmit(): void {
    if (this.userForm.invalid) {
      this.userForm.markAllAsTouched();
      return;
    }

    let serviceCall;
    let msg = 'Creando con éxito';

    if (this.editId) {
      serviceCall = this.userService.edit(this.editId, this.userForm.value);
      msg = 'Actualizado con éxito';
    } else {
      serviceCall = this.userService.post<CreateOrUpdateUser, any>(
        this.userForm.value
      );
    }

    serviceCall.subscribe({
      next: () => {
        alert(msg);
        this.getAll();
        this.editId = null;
        this.initialValues = { ...formEmpty };
        this.onCloseModal();
      },
      error: (error) => {
        console.error(error);
      },
    });
  }

  handleChangeSearch(event: Event): void {
    this.searchQuery = (event.target as HTMLInputElement).value;
    this.getAll(this.searchQuery);
  }

  handleActionEdit(row: GetUser): void {
    this.editId = row.id;
    this.initialValues = { ...row };
    this.userForm.patchValue(row);
    this.showForm = true;
  }

  handleClickDelete(id: string): void {
    if (!id) return;

    const result = confirm('¿Está seguro de que desea eliminar este cliente?');
    if (!result) return;

    this.userService.remove(id).subscribe({
      next: (_) => {
        alert('Cliente eliminado con éxito');
        this.getAll();
      },
      error: (error) => {
        console.error(error);
      },
    });
  }

  handleChangePage(page: number): void {
    this.getAll(this.searchQuery, page);
  }

  handleTableAction(event: { action: string; row: GetUser }): void {
    if (event.action === 'edit') {
      this.handleActionEdit(event.row);
    } else if (event.action === 'delete') {
      this.handleClickDelete(event.row.id);
    }
  }

  openModal(): void {
    this.editId = null;
    this.initialValues = { ...formEmpty };
    this.userForm.reset(formEmpty);
    this.showForm = true;
  }

  onCloseModal(): void {
    this.showForm = false;
    this.userForm.reset(formEmpty);
  }
}
